apiVersion: apps/v1 #version of the API to use
kind: ReplicaSet #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: zn-replicaset
spec: #specifications for our object
  replicas: 2 #The number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: znphp #any pods with labels matching this I'm responsible for.
  template: #The pod template that gets deployed
    metadata:
      labels: #A tag on the pods created
        app: znphp
    spec:
      containers:
      - name: znphp-container #the name of the container within the pod
        image: yenaing/php72 #which container image should be pulled
        ports:
        - containerPort: 80 #the port of the container within the pod
